### ISSUE TITLE
Give me back my hour! State=absent is missing

### ISSUE THREAD

**Issue by krisdante** [zauberpony/ansible-mysql-query#14]
I spent 1 hour to migrate my playbook to this role. Just to read:
`FAILED! => {"changed": false, "msg": "state=absent is not yet implemented"}`

Please include in docs that this is powerpoint-ware and documents feature that does not exist

**Comment by zauberpony** [comment]
Thanks for your kind words! That really motivates me to dig deeper into the problem (in my free time). Spoiler alert: no it doesn't. 

state=absent has been implemented by a (this time really) kind contributor: https://github.com/zauberpony/ansible-mysql-query/commit/49c21be3b6cafd392b2179503be425b38cab2b75

Feel free not to use this module. If you calm down and expect any help, feel free to reopen. Obviously there's a problem, but THIS way is not how to address it.

**Comment by krisdante** [comment]
OK I'm sorry.
I installed this role with the ansible-galaxy. Version form Galaxy works as described in my ticket. It shall be updated there otherwise others will hit the same problem.

**Comment by krisdante** [comment]
I tested version form master and it works now. Sorry for me being asshole.
