### ISSUE TITLE
ansible-galaxy version is outdated

### ISSUE THREAD

**Issue by krisdante** [zauberpony/ansible-mysql-query#15]
ansible-galaxy installs some old version of the role that does not reflect the most recent docs.

**Comment by zauberpony** [comment]
Okay, this two lines seemed to do the trick, Ansible-galaxy now said it imported successfully (without me clicking any button). Thus simple tagging should be enough to release the module.

Thanks for bringing this to my attention, that will safe other users the frustation you experienced.
