### ISSUE TITLE
ansible-galaxy version is outdated

### ISSUE THREAD

**Issue by plemelin** [zauberpony/ansible-mysql-query#20]
I tested the installation of the plugin over ansible-galaxy and it seems it is installation the previous version. (That is incompatible with ansible `2.7.2`.

```
[vagrant@localhost ~]$ ansible-galaxy install zauberpony.mysql-query
- downloading role 'mysql-query', owned by zauberpony
- downloading role from https://github.com/zauberpony/ansible-mysql-query/archive/v0.2.tar.gz
- extracting zauberpony.mysql-query to /home/vagrant/.ansible/roles/zauberpony.mysql-query
- zauberpony.mysql-query (v0.2) was installed successfully
```

**Comment by plemelin** [comment]
@zauberpony Just hum. I just realized the version deploy by galaxy is v0.2 and the latest available tag is v0.5

I ran all the tests from the trunk, so I suppose it's safe to tag have a new tag at the head and use it on the for the ansible-galaxy version.

**Comment by zauberpony** [comment]
Hey, thanks once again. This has already been a problem once, I thought it was fixed... but it seems something slipped through.

Ansible-Galaxy did not update the version, because...

> Galaxy will only import git tags that match the semantic version format, skipping these tag(s): v0.4, v0.5, v0.1, v0.3

**Comment by zauberpony** [comment]
Fixed now:

`$ ansible-galaxy install -p . zauberpony.mysql-query                                                                                                                                                                                         
- downloading role 'mysql-query', owned by zauberpony
- downloading role from https://github.com/zauberpony/ansible-mysql-query/archive/v0.5.1.tar.gz
- extracting zauberpony.mysql-query to /tmp/tmp.3wn9e0TZ15/zauberpony.mysql-query
- zauberpony.mysql-query (v0.5.1) was installed successfully`
