### ISSUE TITLE
Add support for lookups

### ISSUE THREAD

**Issue by jalbstmeijer** [zauberpony/ansible-mysql-query#5]
Hi,

Not sure, but going through the introduction it seems not to be suitable to use mysql to lookup values to use in a playbook?

If true, would that be something that you would consider adding?

Gr, Justin

**Comment by zauberpony** [comment]
Nope, looking up values is not possible, and I would say out of scope of this module, analoguesly to [file](http://docs.ansible.com/ansible/file_module.html) with respect to *template*/*copy* etc. and [stat](http://docs.ansible.com/ansible/stat_module.html). 

But you can achieve something similar with:

```
---
- hosts: all
  tasks:
    - name: lookup icinga_dbversion
      command: mysql -N -e 'select version from icinga_dbversion;' icinga2
      register: icinga_dbversion

    - debug: var=icinga_dbversion.stdout

```

Admittedly it's not very nice… A "mysql-lookup" module like the *stat* module would be nice.

**Comment by zauberpony** [comment]
Ok, I'm closing this issue for now. I'm tempted to say I'll write a module "mysql_fetch"/"mysql_stat" that allows to execute "select"-queries to lookup values, but I have so many other things on my TODO-list first (like e.g. polishing this module first).
